# maven-gitlab-ci.yml


# **注意格式是yml，不是yaml**

stages:
  - build
  - deploy

build:
  stage: build
  tags:
    - build
  only: # limit the branch
    - main
  script:
    - echo "maven clean"
    - echo "maven install"

deploy:
  stage: deploy
  tags:
    - deploy
  only:
    - main
  script:
    - echo "hello deploy"
